kind: Service
apiVersion: v1
metadata:
  name: cmsmonit-spark
  namespace: argo
spec:
  selector:
    app: cmsmonit-spark
  type: NodePort
  ports:
  - name: port-0 # spark.driver.port
    nodePort: 31234
    port: 31234
    protocol: TCP
    targetPort: 31234
  - name: port-1 # spark.driver.blockManager.port
    nodePort: 31235
    port: 31235
    protocol: TCP
    targetPort: 31235
